name: Test SIMBA on Windows

on: 
  push:
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy pandas numba tqdm
        
    - name: Test SIMBA functionality on Windows
      run: |
        python -c "
        import sys; sys.path.insert(0, '.')
        import simba_chem.core as core
        import simba_chem.calculus as calc
        import simba_chem.helpers as helpers
        import numpy as np
        print('Testing basic functionality...')
        
        # Test some basic operations
        test_array = np.array([1, 2, 3, 4, 5])
        print('Numpy operations work:', np.sum(test_array))
        
        # Test file path operations (Windows uses backslashes)
        import os
        print('Current working directory:', os.getcwd())
        print('Package directory contents:', os.listdir('simba_chem'))
        
        print('All basic functionality tests passed on Windows!')
        "
