name: Test SIMBA on Windows

on: 
  push:
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy pandas numba tqdm
        
    - name: Test SIMBA complete workflow on Windows
      run: |
        python -c "
        import sys; sys.path.insert(0, '.')
        import simba_chem as simba
        import os
        
        print('Testing complete SIMBA workflow on Windows...')
        print('Available test files:', os.listdir('tests'))
        
        # Test the typical usage pattern with correct paths
        print('Step 1: Creating input file...')
        simba.create_input('tests/input_file.dat')
        print('Input file created successfully')
        
        print('Step 2: Initializing SIMBA network...')
        network = simba.Simba()
        network.init_simba('tests/input_file.dat')
        print('Network initialized successfully')
        
        print('Step 3: Solving network...')
        result = network.solve_network()
        print('Network solved successfully!')
        print('Result type:', type(result))
        
        print('COMPLETE SIMBA WORKFLOW WORKS ON WINDOWS!')
        "
