name: Test SIMBA on Windows

on: 
  push:
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy pandas numba tqdm
        
    - name: Test SIMBA package imports on Windows
      run: |
        python -c "import sys; sys.path.insert(0, '.'); import simba_chem.core as core; print('Core module works on Windows')"
        python -c "import sys; sys.path.insert(0, '.'); import simba_chem.analysis as analysis; print('Analysis module works on Windows')"
        python -c "import sys; sys.path.insert(0, '.'); import simba_chem.calculus as calculus; print('Calculus module works on Windows')"
        python -c "import sys; sys.path.insert(0, '.'); import simba_chem.helpers as helpers; print('Helpers module works on Windows')"
