name: Test SIMBA on Windows

on: 
  push:
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Test SIMBA on Windows
      run: |
        dir
        cd simba_chem
        python -c "print('Testing Python on Windows')"
        python -c "import sys; print('Python version:', sys.version)"
        python -c "import core; print('Core module works on Windows!')"
        python -c "import analysis; print('Analysis module works on Windows!')"
        python -c "import calculus; print('Calculus module works on Windows!')"
